# version: '3.8'

services:
  unitree_sim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROBOT_TYPE=Go2
    container_name: unitree_sim
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/root/ros2_ws:rw
    stdin_open: true
    tty: true
    privileged: true
    command: bash