x-basic: &basic
  ipc: host
  stdin_open: true
  network_mode: host
  tty: true
  privileged: true
  environment:
    DISPLAY:
    XAUTHORITY: "/root/.Xauthority"
    QT_X11_NO_MITSHM: "1"
    XDG_RUNTIME_DIR:
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ${HOME}/.Xauthority:/root/.Xauthority

x-gui_env: &env_gui
  DISPLAY:
  XAUTHORITY: "/root/.Xauthority"
  QT_X11_NO_MITSHM: "1"
  XDG_RUNTIME_DIR:

services:
  simulator:
    <<: *basic
    image: walking_robot_sim:latest
    container_name: walking_robot_sim
    command: bash -c "tail -f /dev/null" 
    environment:
      <<: *env_gui
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      GAZEBO_RESOURCE_PATH: "/usr/share/gazebo-11"
      GZ_SIM_RESOURCE_PATH: "/root/ws/src/gazebo_sim/models/"
      GAZEBO_MODEL_PATH: "/usr/share/gazebo-11/models/:/opt/ros/jazzy/share/turtlebot3_gazebo/models/"
      CYCLONEDDS_URI: file:///cyclonedds.xml
      ROS_DOMAIN_ID: 0
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BASE_IMG: osrf/ros:jazzy-desktop
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
      - ./../:/root/ws/src/