amcl:
  ros__parameters:
    use_sim_time: False # Не использовать симуляционное время (использовать системное)
    alpha1: 0.2 # Шум вращения при вращении
    alpha2: 0.2 # Шум трансляции при вращении
    alpha3: 0.2 # Шум трансляции при трансляции
    alpha4: 0.2 # Шум вращения при трансляции
    alpha5: 0.2 # Дополнительный шум для улучшенной модели
    base_frame_id: "base_link" # Имя фрейма робота
    beam_skip_distance: 0.5 # Дистанция, при которой лучи будут пропущены (если они близки)
    beam_skip_error_threshold: 0.9 # Порог ошибки, при котором AMCL перестает пропускать лучи
    beam_skip_threshold: 0.3 # Доля лучей, которая может быть пропущена
    do_beamskip: false # Отключить пропускание лучей (ускорение)
    global_frame_id: "map" # Глобальная карта
    lambda_short: 0.1 # Параметр экспоненциального распределения для коротких замеров
    laser_likelihood_max_dist: 2.0 # Максимальное расстояние, на которое учитывается совпадение луча
    laser_max_range: 100.0 # Максимальный диапазон лазера
    laser_min_range: -1.0 # Минимальный диапазон лазера (-1 отключает)
    laser_model_type: "likelihood_field" # Модель измерения для лазера
    max_beams: 60 # Максимальное количество лучей, используемых при оценке
    max_particles: 2000 # Максимальное количество частиц в фильтре частиц
    min_particles: 500 # Минимальное количество частиц
    odom_frame_id: "odom" # Рамка одометрии
    pf_err: 0.05 # Предполагаемая ошибка позиции
    pf_z: 0.99 # Вероятность покрытия истинной позиции
    recovery_alpha_fast: 0.0 # Быстрое обновление веса
    recovery_alpha_slow: 0.0 # Медленное обновление веса
    resample_interval: 1 # Интервал ресемплинга в итерациях
    robot_model_type: "nav2_amcl::DifferentialMotionModel" # Тип модели движения робота
    save_pose_rate: 0.5 # Частота сохранения позиции в секунду
    sigma_hit: 0.2 # Стандартное отклонение для модели попадания
    tf_broadcast: True # Публиковать transform map->odom
    transform_tolerance: 1.0 # Допуск для tf
    update_min_a: 0.2 # Минимальное угловое смещение для обновления
    update_min_d: 0.25 # Минимальное линейное смещение для обновления
    z_hit: 0.5 # Вес модели попадания
    z_max: 0.05 # Вес модели максимального расстояния
    z_rand: 0.5 # Вес случайного измерения
    z_short: 0.05 # Вес коротких замеров
    scan_topic: scan # Топик с лазерными сканами
    set_initial_pose: True # Установить начальную позицию вручную
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.785 # Начальный угол (в радианах, ~45 градусов)

amcl_map_client:
  ros__parameters:
    use_sim_time: False # Использовать реальное время

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False # Использовать реальное время

bt_navigator:
  ros__parameters:
    use_sim_time: False # Используется реальное время (а не симулированное)
    global_frame: map # Глобальная опорная система координат для навигации
    robot_base_frame: base_link # Базовая рамка робота (обычно в центре корпуса)
    odom_topic: /odom # Топик одометрии, на который опирается навигация
    bt_loop_duration: 10 # Интервал обновления поведения (в мс), т.е. 100 Гц
    default_server_timeout: 20 # Таймаут ответа от Action-серверов (в секундах)
    enable_groot_monitoring: True # Включить мониторинг поведения через Groot
    groot_zmq_publisher_port: 1666 # Порт ZMQ для публикации состояния BT
    groot_zmq_server_port: 1667 # Порт ZMQ для получения команды от Groot
    plugin_lib_names: # Список Behavior Tree-плагинов, используемых в навигации
      - nav2_compute_path_to_pose_action_bt_node # Построение пути к позе
      - nav2_compute_path_through_poses_action_bt_node # Через несколько точек
      - nav2_follow_path_action_bt_node # Следование по пути
      - nav2_back_up_action_bt_node # Отъезд назад
      - nav2_spin_action_bt_node # Поворот на месте
      - nav2_wait_action_bt_node # Ожидание
      - nav2_clear_costmap_service_bt_node # Очистка costmap'а
      - nav2_is_stuck_condition_bt_node # Проверка "застрял ли"
      - nav2_goal_reached_condition_bt_node # Цель достигнута?
      - nav2_goal_updated_condition_bt_node # Цель была обновлена?
      - nav2_initial_pose_received_condition_bt_node # Получена ли начальная поза?
      - nav2_reinitialize_global_localization_service_bt_node # Повторная локализация
      - nav2_rate_controller_bt_node # Управление скоростью через BT
      - nav2_distance_controller_bt_node # Управление на основе расстояния
      - nav2_speed_controller_bt_node # Управление на основе скорости
      - nav2_truncate_path_action_bt_node # Усечение пути
      - nav2_goal_updater_node_bt_node # Обновление целей
      - nav2_recovery_node_bt_node # Вызов восстановления
      - nav2_pipeline_sequence_bt_node # Последовательность действий
      - nav2_round_robin_node_bt_node # Выполнение нескольких ветвей по очереди
      - nav2_transform_available_condition_bt_node # Проверка наличия TF
      - nav2_time_expired_condition_bt_node # Истечение времени
      - nav2_distance_traveled_condition_bt_node # Проверка пройденного пути
      - nav2_single_trigger_bt_node # Одноразовый триггер
      - nav2_is_battery_low_condition_bt_node # Проверка уровня заряда (если реализовано)
      - nav2_navigate_through_poses_action_bt_node # Навигация через множество поз
      - nav2_navigate_to_pose_action_bt_node # Навигация к одной позе
      - nav2_remove_passed_goals_action_bt_node # Удаление пройденных целей
      - nav2_planner_selector_bt_node # Выбор планировщика
      - nav2_controller_selector_bt_node # Выбор контроллера
      - nav2_goal_checker_selector_bt_node # Выбор способа проверки достижения цели

# Здесь указано отдельно, чтобы и узел, и компонент bt_navigator использовали одинаковое время.
bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False # Используем реальное время
    controller_frequency: 20.0 # Частота обновления команд управления (Гц)
    min_x_velocity_threshold: 0.001 # Порог по скорости X, ниже которого считается нулём
    min_y_velocity_threshold: 0.5 # Не используется (y=0 в диф. приводе)
    min_theta_velocity_threshold: 0.001 # Порог по угловой скорости
    failure_tolerance: 0.3 # Время в сек., до которого ошибки во время движения игнорируются
    progress_checker_plugin: "progress_checker" # Проверка прогресса движения
    goal_checker_plugins: ["general_goal_checker"] # Проверка достижения цели
    controller_plugins: ["FollowPath"] # Используемый контроллер (DWB)

    # Проверка прогресса
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5 # Минимальное движение (в м), чтобы считалось прогрессом
      movement_time_allowance: 10.0 # Через сколько секунд без движения считается, что застрял

    # Проверка достижения цели
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25 # Допустимая ошибка по положению (в м)
      yaw_goal_tolerance: 0.25 # Допустимая ошибка по ориентации (в рад)

    # DWB (Dynamic Window Approach) — локальный планировщик
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True # Вывод деталей траектории в debug
      min_vel_x: 0.0
      min_vel_y: 0.0 # Для дифференциального привода y=0
      max_vel_x: 0.4
      max_vel_y: 0.0
      max_vel_theta: 0.75 # Максимальная угловая скорость
      min_speed_xy: 0.0
      max_speed_xy: 0.4
      min_speed_theta: 0.0
      acc_lim_x: 2.5 # Линейное ускорение
      acc_lim_y: 0.0
      acc_lim_theta: 3.2 # Угловое ускорение
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20 # Количество образцов по x-скорости
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7 # Время вперёд для симуляции движения
      linear_granularity: 0.05 # Шаг по расстоянию в симуляции
      angular_granularity: 0.025 # Шаг по углу
      transform_tolerance: 0.2 # Допуск при получении TF
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25 # При какой скорости считается, что робот остановился
      short_circuit_trajectory_evaluation: True # Прерывать оценку при плохой траектории
      stateful: True

      # Критерии оценки траекторий
      critics: [
          "RotateToGoal", # Разворот к цели
          "Oscillation", # Предотвращение колебаний
          "BaseObstacle", # Учет препятствий
          "GoalAlign", # Выравнивание по цели
          "PathAlign", # Выравнивание по пути
          "PathDist", # Расстояние до пути
          "GoalDist", # Расстояние до цели
        ]
      BaseObstacle.scale: 0.02 # Вес критерия препятствий
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0 # Считать из всех времён вперёд

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

# local_costmap используется для локального планирования и обхода препятствий,
# опирается на данные с датчиков в реальном времени.
# Эта карта движется вместе с роботом (rolling window), и у неё ограниченный размер (например, 3×3 м).
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 # Частота обновления costmap (Гц). Хорошо подходит для большинства роботов.
      publish_frequency: 2.0 # Частота публикации costmap для RViz и других узлов (Гц).
      global_frame: odom # Глобальная система координат для этой карты (обычно `odom` для локального планирования).
      robot_base_frame: base_link # Кадр, связанный с телом робота.
      use_sim_time: False # Использование реального времени.
      rolling_window: True # Активирует "плавающее окно", т.е. карта движется вместе с роботом.
      width: 3 # Ширина карты в метрах
      height: 3 # Высота карты в метрах
      resolution: 0.05 # Разрешение (5 см/клетка) — хорошее соотношение детализации и производительности
      robot_radius: 0.22 # Радиус робота (используется для инфляции и обхода препятствий)
      # plugins: ["voxel2d_layer", "voxel3d_layer", "inflation_layer"]
      plugins: ["voxel2d_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel2d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      # voxel3d_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   publish_voxel_map: False
      #   origin_z: 0.0
      #   z_resolution: 0.05
      #   z_voxels: 16
      #   mark_threshold: 1
      #   observation_sources: realsense zed
      #   min_obstacle_height: 0.00
      #   max_obstacle_height: 2.0
      #   realsense:
      #     topic: /camera/depth/color/points
      #     raytrace_min_range: 0.5
      #     min_obstacle_height: 0.0
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "PointCloud2"
      #   zed:
      #     topic: /zed/point_cloud/cloud_registered
      #     raytrace_min_range: 0.5
      #     min_obstacle_height: 0.0
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: True
      plugins:
        # ["static_layer", "voxel2d_layer", "voxel3d_layer", "inflation_layer"]
        ["static_layer", "voxel2d_layer", "inflation_layer"]
      voxel2d_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        publish_voxel_map: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      # voxel3d_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   publish_voxel_map: True
      #   origin_z: 0.0
      #   z_resolution: 0.05
      #   z_voxels: 16
      #   mark_threshold: 1
      #   observation_sources: realsense zed
      #   min_obstacle_height: 0.00
      #   max_obstacle_height: 2.0
      #   realsense:
      #     topic: /camera/depth/color/points
      #     raytrace_min_range: 0.5
      #     min_obstacle_height: 0.0
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "PointCloud2"
      #   zed:
      #     topic: /zed/point_cloud/cloud_registered
      #     raytrace_min_range: 0.5
      #     min_obstacle_height: 0.0
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: True

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
